# This is a basic workflow to help you get started with Actions

name: DeployToAKS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: docker build
        run: docker build -t image:'${{github.sha}}'
        
      - name: docker login
        run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'  
        
      - name: docker tag
        run: docker tag image:'${{github.sha}}' '${{secrets.DOCKER_LOGIN}}'/image:'${{github.sha}}'
        
      - name: docker push
        run: docker push '${{secrets.DOCKER_LOGIN}}'/image:'${{github.sha}}'        
