apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
data:
  index.html: |
    <title>Welcome to nginx which we created</title>
    <h1>Welcome to our own nginx!</h1>
#  Name: Kaushik
#  Company: Nexturn